#!/bin/bash
# this script copies /var/log contents and clears current content of the file
# usage : ./clearlogs

cp /var/log/messages /var/log/messages.old
cat /dev/null > /var/log/messages
echo log file copied and cleaned up

exit 0
