#!/bin/bash
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak &&
#vim /etc/ssh/sshd_config 
echo "PermitRootLogin no" > /etc/ssh/sshd_config &&
echo "PasswordAuthentication no" > /etc/ssh/sshd_config &&
sshd -t &&
service sshd restart


exit 0
