#!/bin/bash
#https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-a-centos-7-server

wget http://nodejs.org/dist/v0.10.30/node-v0.10.30.tar.gz &&
tar xzvf node-v*  &&
sleep 3 &&
cd node-v*   &&

sleep 3 &&
sudo yum install gcc gcc-c++ &&
./configure  &&
sleep 3 &&
make  &&
sudo make install  &&
sleep 3 &&
#echo $node --version &&

# https://www.npmjs.com/package/json2yaml

npm install -g json2yaml  &&
npm install -g yamljs  &&
# to run use json2yaml the file example.json >  example.yml







exit 0
